- name: Fetch and Encode Nodes
        run: |
          # 换成这个纯净的高可用混合源链接
          curl -s -L --connect-timeout 30 --retry 3 'https://raw.githubusercontent.com/vfarid/v2ray-share/main/all_links.txt' > raw_nodes.txt
          
          if [ ! -s raw_nodes.txt ]; then
            echo "Error: Fetched empty data"
            exit 1
          fi
          
          # 保持 base64 整体转码打包
          base64 -w 0 raw_nodes.txt > nodes.txt
